# Generated by Django 5.2.1 on 2025-11-01 21:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=255)),
                ("checksum", models.CharField(max_length=64, unique=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("page_count", models.PositiveIntegerField(default=0)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "doc_document",
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("index", models.PositiveBigIntegerField()),
                ("text_excerpt", models.TextField(blank=True)),
                ("tag", models.CharField(blank=True, max_length=64)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="core.document",
                    ),
                ),
            ],
            options={
                "db_table": "doc_page",
            },
        ),
        migrations.CreateModel(
            name="ParseJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Succes"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("errors_json", models.JSONField(blank=True, default=list)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parse_jobs",
                        to="core.document",
                    ),
                ),
            ],
            options={
                "db_table": "doc_parse_job",
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.CharField(
                        choices=[("INFO", "Info"), ("WARN", "Warn"), ("ERROR", "Error")],
                        default="INFO",
                        max_length=8,
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="core.parsejob",
                    ),
                ),
            ],
            options={
                "db_table": "doc_audit_event",
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("version", models.CharField(default="1.0", max_length=32)),
                ("description", models.TextField(blank=True)),
                ("rules_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "doc_template",
                "indexes": [models.Index(fields=["created_at"], name="tpl_created_idx")],
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="ReorderRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("spec_json", models.JSONField(blank=True, default=dict)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reorder_rules",
                        to="core.template",
                    ),
                ),
            ],
            options={
                "db_table": "doc_reorder_rule",
            },
        ),
        migrations.CreateModel(
            name="ExtractedField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=128)),
                ("value", models.TextField(blank=True)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_fields",
                        to="core.document",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fields",
                        to="core.template",
                    ),
                ),
            ],
            options={
                "db_table": "doc_extracted_field",
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["created_at"], name="doc_created_idx"),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(fields=["document"], name="page_document_idx"),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(fields=["created_at"], name="page_created_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="page",
            unique_together={("document", "index")},
        ),
        migrations.AddIndex(
            model_name="parsejob",
            index=models.Index(fields=["document"], name="job_document_idx"),
        ),
        migrations.AddIndex(
            model_name="parsejob",
            index=models.Index(fields=["created_at"], name="job_created_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["job"], name="ae_job_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["created_at"], name="ae_created_idx"),
        ),
        migrations.AddIndex(
            model_name="reorderrule",
            index=models.Index(fields=["template"], name="rr_template_idx"),
        ),
        migrations.AddIndex(
            model_name="reorderrule",
            index=models.Index(fields=["created_at"], name="rr_created_idx"),
        ),
        migrations.AddIndex(
            model_name="extractedfield",
            index=models.Index(fields=["document"], name="ef_document_idx"),
        ),
        migrations.AddIndex(
            model_name="extractedfield",
            index=models.Index(fields=["template"], name="ef_template_idx"),
        ),
        migrations.AddIndex(
            model_name="extractedfield",
            index=models.Index(fields=["created_at"], name="ef_created_idx"),
        ),
    ]
