# Generated by Django 5.2.1 on 2025-11-06 07:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_seed_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsejob",
            name="job_uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="parsejob",
            name="output_pdf_path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parsejob",
            name="result_fields",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parsejob",
            name="result_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parsejob",
            name="result_pages",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
