# Generated by Django 5.2.1 on 2025-11-06 07:22

import uuid

from django.db import migrations


def populate_job_uuid(apps, schema_editor):
    ParseJob = apps.get_model("core", "ParseJob")
    # Iterate to ensure each row gets a unique value
    for job in ParseJob.objects.filter(job_uuid__isnull=True).only("id").iterator():
        job.job_uuid = uuid.uuid4()
        job.save(update_fields=["job_uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_parsejob_job_uuid_parsejob_output_pdf_path_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_job_uuid, migrations.RunPython.noop),
    ]
