# Generated by Django 5.2.1 on 2025-11-07 20:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_populate_job_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parsejob",
            name="job_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name="parsejob",
            index=models.Index(fields=["job_uuid"], name="job_uuid_idx"),
        ),
    ]
