# Generated by Django 5.2.1 on 2025-11-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_enforce_job_uuid_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsejob",
            name="signature_pdf_path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="parsejob",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("SUCCESS", "Success"), ("FAILED", "Failed")],
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
