# Generated by Django 5.2.1 on 2025-11-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_parsejob_signature_pdf_path_alter_parsejob_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsejob",
            name="payment_voucher_pdf_path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
