# Generated by Django 5.2.1 on 2026-06-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_parsejob_disposition_and_tin_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsejob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('APPLIED', 'Applied')], default='PENDING', max_length=16),
        ),
    ]
