# Generated by Django 5.2.1 on 2025-06-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaluser',
            name='role',
            field=models.CharField(choices=[('office_admin', 'Office Admin'), ('data_entry_specialist', 'Data Entry Specialist'), ('i_t_technician', 'IT Technician'), ('tax_preparer', 'Tax Preparer'), ('billing', 'Billing Agent'), ('reviewer', 'Reviewer'), ('manager', 'Manager'), ('owner', 'Owner'), ('developer', 'Developer')], max_length=50),
        ),
    ]
