# Generated by Django 5.2.1 on 2025-08-22 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_internaluser_role'),
        ('core', '0026_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaluser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.organization'),
        ),
    ]
