# Generated by Django 5.2.1 on 2025-08-22 07:10

from django.db import migrations


def backfill_orgs(apps, schema_editor):
    Organization = apps.get_model("core", "Organization")
    User = apps.get_model("accounts", "InternalUser")

    # cerate a default org if none exist, else reuse the first one
    default_org = Organization.objects.first()
    if default_org is None:
        default_org = Organization.objects.create(name = "Default Org")
    
    # attach any users missing an org to the default org
    User.objects.filter(organization__isnull = True).update(organization = default_org)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_organization"),
        ('accounts', '0003_internaluser_organization'),
    ]

    operations = [
        migrations.RunPython(backfill_orgs, migrations.RunPython.noop),
    ]
