# Generated by Django 5.2.1 on 2025-08-22 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_user_orgs'),
        ('core', '0026_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaluser',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.organization'),
        ),
    ]
