# Generated by Django 5.2.1 on 2025-06-02 04:02

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIN', models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[core.models.validate_TIN])),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=10, null=True, validators=[core.models.validate_phone])),
                ('filing_type', models.CharField(blank=True, choices=[('', ''), ('Simple', 'Simple'), ('Credits', 'Credits'), ('Itemizing', 'Itemizing'), ('Itemizing', 'Sole Proprietor'), ('Corporation', 'Corporation')], default='', max_length=100, null=True)),
                ('prior_filing_type', models.CharField(blank=True, choices=[('', ''), ('Simple', 'Simple'), ('Credits', 'Credits'), ('Itemizing', 'Itemizing'), ('Sole Proprietor', 'Sole Proprietor'), ('Corporation', 'Corporation')], default='', max_length=100, null=True)),
                ('appointment_type', models.CharField(blank=True, choices=[('', ''), ('DROP OFF', 'DROP OFF'), ('OFFICE', 'OFFICE'), ('ONLINE', 'ONLINE'), ('TBD', 'TBD')], default='', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, choices=[('', ''), ('Personal Taxes', 'Personal Taxes'), ('Corporate Taxes', 'Corporate Taxes'), ('Extension', 'Extension'), ('Amendment', 'Amendment'), ('Withholdings Adjustment', 'Withholdings Adjustment'), ('Advisory', 'Advisory'), ('Reject Correction', 'Reject Correction')], default='', max_length=100, null=True)),
                ('default_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('', ''), ('TPG', 'TPG'), ('QBO', 'QBO'), ('CASH', 'CASH'), ('SQUARE', 'SQUARE'), ('CHECK', 'CHECK'), ('OTHER APPLICATION', 'OTHER APPLICATION'), ('NO FEE - PRO BONO', 'NO FEE - PRO BONO'), ('NO FEE - DEPENDENT', 'NO FEE - DEPENDENT'), ('TBD', 'TBD')], default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[core.models.validate_tax_year])),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('R', 'R')], default='', max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='DailyClearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_clearing', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.product')),
                ('tax_preparer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(validators=[core.models.validate_tax_year])),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_years', to='core.client')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tax_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.taxyear'),
        ),
    ]
