# Generated by Django 5.2.1 on 2025-06-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='filing_type',
            field=models.CharField(blank=True, choices=[('', ''), ('Simple', 'Simple'), ('Credits', 'Credits'), ('Itemizing', 'Itemizing'), ('Sole Proprietor', 'Sole Proprietor'), ('Corporation', 'Corporation')], default='', max_length=100, null=True),
        ),
    ]
