# Generated by Django 5.2.1 on 2025-06-22 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_client_filing_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True, help_text='When True season is UI visible. When False season is hidden from UI.')),
                ('is_locked', models.BooleanField(default=False, help_text='When True data cannot be edited. When False data is mutable.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.AlterModelOptions(
            name='intake',
            options={'verbose_name': 'Intake', 'verbose_name_plural': 'Intakes'},
        ),
        migrations.AddField(
            model_name='acknowledgment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='core.product'),
        ),
        migrations.AlterField(
            model_name='dailyclearing',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_clearings', to='core.client'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='core.client'),
        ),
        migrations.AddIndex(
            model_name='productassignment',
            index=models.Index(fields=['tax_preparer', 'product'], name='core_produc_tax_pre_7c41eb_idx'),
        ),
        migrations.AddField(
            model_name='acknowledgment',
            name='tax_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgments', to='core.taxseason'),
        ),
        migrations.AddField(
            model_name='dailyclearing',
            name='tax_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_clearings', to='core.taxseason'),
        ),
        migrations.AddField(
            model_name='intake',
            name='tax_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intakes', to='core.taxseason'),
        ),
        migrations.AlterUniqueTogether(
            name='acknowledgment',
            unique_together={('product', 'tax_season')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyclearing',
            unique_together={('client', 'tax_season')},
        ),
        migrations.AlterUniqueTogether(
            name='intake',
            unique_together={('client', 'tax_season')},
        ),
        migrations.AddIndex(
            model_name='acknowledgment',
            index=models.Index(fields=['product', 'tax_season'], name='core_acknow_product_b14bec_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyclearing',
            index=models.Index(fields=['client', 'tax_season'], name='core_dailyc_client__6fcfb0_idx'),
        ),
        migrations.AddIndex(
            model_name='intake',
            index=models.Index(fields=['client', 'tax_season'], name='core_intake_client__522c7c_idx'),
        ),
        migrations.RemoveField(
            model_name='acknowledgment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='acknowledgment',
            name='year',
        ),
    ]
