# Generated by Django 5.2.1 on 2025-06-23 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_taxseason_alter_intake_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='core.product'),
        ),
        migrations.AlterField(
            model_name='acknowledgment',
            name='tax_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgments', to='core.taxseason'),
        ),
        migrations.AlterField(
            model_name='dailyclearing',
            name='tax_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_clearings', to='core.taxseason'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='tax_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intakes', to='core.taxseason'),
        ),
    ]
