# Generated by Django 5.2.1 on 2025-06-25 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_acknowledgment_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes', to='core.product'),
        ),
    ]
