# Generated by Django 5.2.1 on 2025-06-25 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_intake_product'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productassignment',
            name='core_produc_tax_pre_7c41eb_idx',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productassignment',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='productassignment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='productassignment',
            name='tax_preparer',
        ),
        migrations.AddField(
            model_name='productassignment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='core.client'),
        ),
        migrations.AddField(
            model_name='productassignment',
            name='intake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='core.intake'),
        ),
        migrations.AddField(
            model_name='productassignment',
            name='tax_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='core.taxyear'),
        ),
        migrations.AlterField(
            model_name='productassignment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='core.product'),
        ),
    ]
