# Generated by Django 5.2.1 on 2025-06-25 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_productassignment_core_produc_tax_pre_7c41eb_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productassignment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='core.client'),
        ),
        migrations.AlterField(
            model_name='productassignment',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='core.intake'),
        ),
        migrations.AlterField(
            model_name='productassignment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='core.product'),
        ),
        migrations.AlterField(
            model_name='productassignment',
            name='tax_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='core.taxyear'),
        ),
    ]
