# Generated by Django 5.2.1 on 2025-06-26 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_productassignment_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_type', models.CharField(blank=True, choices=[('', ''), ('Simple', 'Simple'), ('Credits', 'Credits'), ('Itemizing', 'Itemizing'), ('Sole Proprietor', 'Sole Proprietor'), ('Corporation', 'Corporation')], default='', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='productassignment',
            name='filing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_assignments', to='core.filingtype'),
        ),
    ]
