# Generated by Django 5.2.1 on 2025-06-27 19:58

from django.db import migrations

def seed_filing_types(apps, schema_editor):
    FilingType = apps.get_model('core', 'FilingType')
    choices = [
        'TBD',
        'Simple',
        'Credits',
        'Itemizing',
        'Sole Proprietor',
        'Corporation',
    ]
    for label in choices:
        FilingType.objects.get_or_create(filing_type=label)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_filingtype_productassignment_filing_type'),
    ]

    operations = [
        migrations.RunPython(seed_filing_types, reverse_code=migrations.RunPython.noop),
    ]
