# Generated by Django 5.2.1 on 2025-06-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_filing_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filingtype',
            name='filing_type',
            field=models.CharField(blank=True, choices=[('TBD', 'TBD'), ('Simple', 'Simple'), ('Credits', 'Credits'), ('Itemizing', 'Itemizing'), ('Sole Proprietor', 'Sole Proprietor'), ('Corporation', 'Corporation')], default='TBD', max_length=100, null=True),
        ),
    ]
