# Generated by Django 5.2.1 on 2025-06-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_filingtype_filing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgment',
            name='status',
            field=models.CharField(blank=True, choices=[('TBD', 'TBD'), ('A', 'A'), ('R', 'R')], default='TBD', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('TBD', ''), ('TPG', 'TPG'), ('QBO', 'QBO'), ('CASH', 'CASH'), ('SQUARE', 'SQUARE'), ('CHECK', 'CHECK'), ('OTHER APPLICATION', 'OTHER APPLICATION'), ('NO FEE - PRO BONO', 'NO FEE - PRO BONO'), ('NO FEE - DEPENDENT', 'NO FEE - DEPENDENT')], default='TBD', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('TBD', 'TBD'), ('Personal Taxes', 'Personal Taxes'), ('Corporate Taxes', 'Corporate Taxes'), ('Extension', 'Extension'), ('Amendment', 'Amendment'), ('Withholdings Adjustment', 'Withholdings Adjustment'), ('Advisory', 'Advisory'), ('Reject Correction', 'Reject Correction')], default='TBD', max_length=100, null=True),
        ),
    ]
