# Generated by Django 5.2.1 on 2025-07-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_acknowledgment_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taxyear',
            unique_together={('client', 'year')},
        ),
    ]
