# Generated by Django 5.2.1 on 2025-07-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_taxyear_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('TBD', 'TBD'), ('Personal Taxes', 'Personal Taxes'), ('Corporate Taxes', 'Corporate Taxes'), ('Free Extension', 'Free Extension'), ('Paid Extension', 'Paid Extension'), ('Amendment 1', 'Amendment 1'), ('Amendment 2', 'Amendment 2'), ('Amendment 3', 'Amendment 3'), ('Withholdings Adjustment', 'Withholdings Adjustment'), ('Advisory', 'Advisory'), ('Reject Correction', 'Reject Correction')], default='TBD', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tax_year', 'product_type')},
        ),
    ]
