# Generated by Django 5.2.1 on 2025-07-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_product_active',
            field=models.BooleanField(default=False),
        ),
    ]
