# Generated by Django 5.2.1 on 2025-07-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_is_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productassignment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
