# Generated by Django 5.2.1 on 2025-07-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_productassignment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='acknowledgment',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='True if this acknowledgment is beyond the active IRS e-file window and part of an archived season.'),
        ),
        migrations.AddField(
            model_name='dailyclearing',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intake',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productassignment',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='True if assignment belongs to an archived tax season.'),
        ),
        migrations.AddField(
            model_name='productassignment',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productassignment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('TBD', ''), ('TPG', 'TPG'), ('QBO', 'QBO'), ('CASH', 'CASH'), ('SQUARE', 'SQUARE'), ('CHECK', 'CHECK'), ('OTHER APPLICATION', 'OTHER APPLICATION'), ('NO FEE - PRO BONO', 'NO FEE - PRO BONO'), ('NO FEE - DEPENDENT', 'NO FEE - DEPENDENT')], default='TBD', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taxseason',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acknowledgment',
            name='status',
            field=models.CharField(blank=True, choices=[('TBD', 'TBD'), ('A', 'A'), ('R', 'R'), ('PAPER FILED', 'PAPER FILED')], default='TBD', max_length=15, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productassignment',
            unique_together={('client', 'intake', 'tax_year', 'product')},
        ),
    ]
