# Generated by Django 5.2.1 on 2025-07-29 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_product_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productassignment',
            name='preparer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'tax_preparer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_product_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
