# Generated by Django 5.2.1 on 2025-08-04 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_productassignment_preparer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fee',
        ),
        migrations.AddField(
            model_name='productassignment',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AddField(
            model_name='productassignment',
            name='fee',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
