# Generated by Django 5.2.1 on 2025-08-04 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_product_discount_remove_product_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productassignment',
            name='discount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='productassignment',
            name='fee',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
