# Generated by Django 5.2.1 on 2025-08-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_productassignment_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productassignment',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='productassignment',
            name='fee',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
