# Generated by Django 5.2.1 on 2025-08-04 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_productassignment_discount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('appointment_type', models.CharField(choices=[('', ''), ('Drop Off', 'Drop Off'), ('Office', 'Office'), ('Online', 'Online'), ('TBD', 'TBD')], default='', max_length=20)),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('', ''), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preparer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('product_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='core.productassignment')),
            ],
        ),
    ]
