# Generated by Django 5.2.1 on 2025-08-11 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productassignment',
            name='discount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AddField(
            model_name='productassignment',
            name='fee',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
