# Generated by Django 5.2.1 on 2025-08-15 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_product_discount_remove_product_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productassignment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='productassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('client', 'intake', 'tax_year', 'product'), name='uniq_active_client_intake_taxyear_product'),
        ),
    ]
