# Generated by Django 5.2.1 on 2025-12-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='acknowledgment',
            name='ack_date',
            field=models.DateField(blank=True, help_text='Official date of acknowledgment from government', null=True),
        ),
    ]
