# Generated by Django 5.2.1 on 2025-12-11 08:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_acknowledgment_ack_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='acknowledgment',
            name='core_acknow_product_b14bec_idx',
        ),
        migrations.RenameField(
            model_name='acknowledgment',
            old_name='ack_date',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='acknowledgment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='acknowledgment',
            name='client_name',
            field=models.CharField(blank=True, help_text='Name of client to which acknowledgment belongs', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgment',
            name='client_tin',
            field=models.CharField(blank=True, help_text='TIN as reported in the ACK file (IDNumber).', max_length=9, null=True, validators=[core.models.validate_TIN]),
        ),
        migrations.AddField(
            model_name='acknowledgment',
            name='type',
            field=models.CharField(blank=True, help_text='Form being acknowledged', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgment',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year to which the Acknowledment is for', null=True, validators=[core.models.validate_tax_year]),
        ),
        migrations.AddIndex(
            model_name='acknowledgment',
            index=models.Index(fields=['tax_season', 'year', 'date'], name='core_acknow_tax_sea_703c57_idx'),
        ),
        migrations.AddIndex(
            model_name='acknowledgment',
            index=models.Index(fields=['client_tin'], name='core_acknow_client__bda6ce_idx'),
        ),
    ]
