# Generated by Django 5.2.1 on 2025-12-12 18:55

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_acknowledgment_core_acknow_product_b14bec_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acknowledgment',
            name='product_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgments', to='core.productassignment'),
        ),
        migrations.CreateModel(
            name='AckStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[core.models.validate_tax_year])),
                ('client_tin', models.CharField(blank=True, max_length=9, null=True, validators=[core.models.validate_TIN])),
                ('client_name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('match_state', models.CharField(choices=[('MATCHED', 'Matched'), ('UNMATCHED', 'Unmatched'), ('AMBIGUOUS', 'Ambiguous'), ('DECLINED', 'Declined'), ('NEEDS_FILING_TYPE', 'Needs Filing Type'), ('CLIENT_NOT_FOUND', 'Client Not Found')], default='UNMATCHED', max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('suggested_product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('suggested_tax_season_year', models.PositiveIntegerField(blank=True, null=True)),
                ('resolved_product_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_ack_staging_rows', to='core.productassignment')),
            ],
            options={
                'indexes': [models.Index(fields=['match_state', 'year', 'date'], name='core_acksta_match_s_a6722f_idx'), models.Index(fields=['client_tin'], name='core_acksta_client__0e46cb_idx')],
            },
        ),
    ]
