# Generated by Django 5.2.1 on 2025-12-19 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_acknowledgment_product_assignment_ackstaging'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ackstaging',
            name='expected_ack_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productassignment',
            name='closing_message_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productassignment',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_product_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productassignment',
            name='completion_state',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('PENDING_PARSER', 'Pending Parser'), ('PARSER_RUNNING', 'Parser Running'), ('PARSER_DONE', 'Parser Done'), ('PARSER_SKIPPED', 'Parser Skipped'), ('PENDING_ACK_COUNT', 'Pending Ack Count'), ('READY_TO_COMPLETE', 'Ready to Complete'), ('COMPLETED', 'Completed')], default='OPEN', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='productassignment',
            name='expected_ack_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productassignment',
            name='parser_status',
            field=models.CharField(blank=True, choices=[('NOT_STARTED', 'Not Started'), ('SKIPPED', 'Skipped'), ('DONE', 'Done')], default='NOT_STARTED', max_length=20, null=True),
        ),
    ]
