# Generated by Django 5.2.1 on 2025-12-28 12:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_ackstaging_expected_ack_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAssignmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PA_COMPLETED', 'PA_COMPLETED')], max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_assignment_events', to=settings.AUTH_USER_MODEL)),
                ('product_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.productassignment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product_assignment', 'event_type'), name='uniq_pa_event_type')],
            },
        ),
    ]
