'''
class ProviderError(Exception): ...
class ProviderAuthError(ProviderError): ...
class ProviderRateLimitError(ProviderError): ...
class ProviderValidationError(ProviderError): ...
class ProviderServerError(ProviderError): ...

'''