# Generated by Django 5.2.1 on 2025-09-03 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0026_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qboconnection',
            name='org',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.CreateModel(
            name='QboWebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('intuit_signature', models.CharField(blank=True, max_length=255)),
                ('realm_id', models.CharField(blank=True, max_length=32)),
                ('raw_body', models.TextField()),
                ('json_payload', models.JSONField()),
                ('event_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('error', 'Error')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['received_at'], name='billing_qbo_receive_94e7ea_idx'), models.Index(fields=['realm_id'], name='billing_qbo_realm_i_0cab66_idx'), models.Index(fields=['status'], name='billing_qbo_status_ccb58f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientQboLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(max_length=32)),
                ('qbo_customer_id', models.CharField(max_length=64, unique=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qbo_link', to='core.client')),
            ],
            options={
                'indexes': [models.Index(fields=['realm_id', 'qbo_customer_id'], name='billing_cli_realm_i_49f871_idx')],
                'unique_together': {('realm_id', 'qbo_customer_id')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Sent', 'Sent'), ('Paid', 'Paid'), ('Partial', 'Partial'), ('Failed', 'Failed'), ('Canceled', 'Canceled'), ('Unknown', 'Unknown')], default='Draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('qbo_invoice_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('qbo_customer_id', models.CharField(blank=True, max_length=64, null=True)),
                ('qbo_sync_token', models.CharField(blank=True, max_length=16)),
                ('qbo_last_updated', models.DateTimeField(blank=True, null=True)),
                ('qbo_invoice_number', models.CharField(blank=True, max_length=32)),
                ('qbo_amount_cents', models.BigIntegerField()),
                ('qbo_balance_cents', models.BigIntegerField(default=0)),
                ('qbo_currency', models.CharField(default='USD', max_length=8)),
                ('qbo_txn_date', models.DateField(blank=True, null=True)),
                ('qbo_due_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.client')),
            ],
            options={
                'indexes': [models.Index(fields=['qbo_invoice_id'], name='billing_inv_qbo_inv_aed07c_idx'), models.Index(fields=['qbo_invoice_number'], name='billing_inv_qbo_inv_263b63_idx'), models.Index(fields=['qbo_customer_id'], name='billing_inv_qbo_cus_f97e9e_idx'), models.Index(fields=['client'], name='billing_inv_client__70fb2b_idx'), models.Index(fields=['status'], name='billing_inv_status_541249_idx'), models.Index(fields=['last_synced_at'], name='billing_inv_last_sy_1ad895_idx'), models.Index(fields=['qbo_last_updated'], name='billing_inv_qbo_las_79c09b_idx'), models.Index(fields=['qbo_txn_date'], name='billing_inv_qbo_txn_b88890_idx'), models.Index(fields=['qbo_due_date'], name='billing_inv_qbo_due_2b5f11_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('qbo_amount_cents__gte', 0)), name='invoice_amount_nonnegative'), models.CheckConstraint(condition=models.Q(('qbo_balance_cents__gte', 0)), name='invoice_balance_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='QboEntityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('realm_id', models.CharField(max_length=32)),
                ('entity_name', models.CharField(max_length=32)),
                ('entity_id', models.CharField(max_length=64)),
                ('operation', models.CharField(max_length=32)),
                ('last_updated', models.DateTimeField()),
                ('event_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('processed', 'Processed'), ('error', 'Error')], default='received', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retries', models.PositiveIntegerField(default=0)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_events', to='billing.qbowebhookdelivery')),
            ],
            options={
                'indexes': [models.Index(fields=['realm_id', 'entity_name'], name='billing_qbo_realm_i_f53a49_idx'), models.Index(fields=['status'], name='billing_qbo_status_f48886_idx'), models.Index(fields=['last_updated'], name='billing_qbo_last_up_8c72b6_idx')],
                'unique_together': {('realm_id', 'entity_name', 'entity_id', 'operation', 'last_updated')},
            },
        ),
    ]
