# Generated by Django 5.2.1 on 2025-09-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_qboconnection_org_qbowebhookdelivery_and_more'),
        ('core', '0026_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_qbo_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='qbo_amount_cents',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Sent', 'Sent'), ('Paid', 'Paid'), ('Partial', 'Partial'), ('Voided', 'Voided'), ('Failed', 'Failed'), ('Deleted', 'Deleted'), ('Unknown', 'Unknown')], default='Draft', max_length=16),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'status'], name='billing_inv_client__85c90b_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('qbo_balance_cents__lte', models.F('qbo_amount_cents'))), name='invoice_balance_lte_amount'),
        ),
    ]
