# Generated by Django 5.2.1 on 2025-09-22 07:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_last_qbo_payload_and_more'),
        ('core', '0026_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentInvoiceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_activity_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['last_activity_at'], name='billing_inv_last_ac_345391_idx'),
        ),
        migrations.AddField(
            model_name='assignmentinvoicelink',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_links', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='assignmentinvoicelink',
            name='product_assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_link', to='core.productassignment'),
        ),
        migrations.AddIndex(
            model_name='assignmentinvoicelink',
            index=models.Index(fields=['invoice'], name='billing_ass_invoice_d4140d_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentinvoicelink',
            index=models.Index(fields=['product_assignment'], name='billing_ass_product_02abac_idx'),
        ),
    ]
