"""
Django settings for pdk_crm project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from urllib.parse import urlparse
from distutils.util import strtobool


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load appropriate .env file based on DJANGO_ENV system variable
DJANGO_ENV = os.getenv("DJANGO_ENV", "development").lower()

env_path = BASE_DIR / f".env.{DJANGO_ENV}"
if env_path.exists():
    load_dotenv(env_path)

# QBO / Intuit settings
INTUIT_CLIENT_ID = os.getenv("INTUIT_CLIENT_ID", "").strip()
INTUIT_CLIENT_SECRET = os.getenv("INTUIT_CLIENT_SECRET", "").strip()
INTUIT_REDIRECT_URI = os.getenv("INTUIT_REDIRECT_URI", "").strip()
INTUIT_ENV = os.getenv("INTUIT_ENV", "sandbox").strip()
QBO_WEBHOOK_VERIFIER_TOKEN = os.getenv("QBO_WEBHOOK_VERIFIER_TOKEN", "").strip()
QBO_MINOR_VERSION = int(os.getenv("QBO_MINOR_VERSION", "75").strip() or "75")

FEATURE_QBO = os.getenv("FEATURE_QBO", "True").strip().lower() == "true"
if FEATURE_QBO:
    required = [
        INTUIT_CLIENT_ID, INTUIT_CLIENT_SECRET, INTUIT_REDIRECT_URI, QBO_WEBHOOK_VERIFIER_TOKEN,
    ]
    if any(not v for v in required):
        raise RuntimeError("FEATURE_QBO is enabled but one or more required QBO env vars are missing.")
    
QBO_ENABLE_CARD = os.getenv("QBO_ENABLE_CARD" , "True").strip().lower() == "true"
QBO_ENABLE_ACH = os.getenv("QBO_ENABLE_ACH", "True").strip().lower() == "true"
# QBO_ITEM_SERVICE_ID = os.getenv("QBO_ITEM_SERVICE_ID")  # optional, might be None

# ---- Billing Phase 3 (Provider/Item defaults) ----
BILLING_PROVIDER = os.getenv("BILLING_PROVIDER", "fake").strip().lower()   # "qbo" or "fake"

# Default QBO Item used for MVP invoices (Service item).
# If you already know the Item.Id in your sandbox, set QBO_DEFAULT_ITEM_ID to skip lookup/creation.
QBO_DEFAULT_ITEM_NAME = os.getenv("QBO_DEFAULT_ITEM_NAME", "Tax Preparation").strip()
QBO_DEFAULT_ITEM_ID = os.getenv("QBO_DEFAULT_ITEM_ID", "").strip()


# Quiet period used to determine how soon an invoice is automatically sent after a product assignment as been marked as completed
BILLING_QUIET_PERIOD_MINUTES = int(os.getenv("BILLING_QUIET_PERIOD_MINUTES", "5"))



# SECURITY WARNING: Keep secret key used in production vaulted
SECRET_KEY = os.getenv("SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes")


def _host_only(val: str) -> str:
    '''return the hostname[:port] from a host or URL string'''
    if not val:
        return ""
    val = val.strip()
    if "://" in val:
        return urlparse(val).netloc
    # strip any accidental paths
    return val.split("/")[0]

_env_hosts = [h for h in (os.getenv("ALLOWED_HOSTS", "")).split(",") if h.strip()]
_env_hosts = [_host_only(h) for h in _env_hosts if _host_only(h)]

default_hosts = ["localhost", "127.0.0.1", ".ngrok-free.app"]

_ngrok_env = os.getenv("NGROK_HOST") or os.getenv("NGROK_DOMAIN") or ""
_ngrok_host = _host_only(_ngrok_env)

ALLOWED_HOSTS = sorted(set(default_hosts + _env_hosts + ([_ngrok_host] if _ngrok_host else [])))

CSRF_TRUSTED_ORIGINS = []
for h in ALLOWED_HOSTS:
    if h in ("localhost", "127.0.0.1", ".ngrok-free.app"):
        continue
    CSRF_TRUSTED_ORIGINS.append(f"https://{h}")

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "http")

'''
# ALLOWED_HOSTS should be a comma-separated list in the .env file
ALLOWED_HOSTS = [host.strip() for host in os.getenv("ALLOWED_HOSTS", "").split(",") if host]

# CSRF trusted origins for Django 4+
CSRF_TRUSTED_ORIGINS = [f"https://{h}" for h in ALLOWED_HOSTS if h not in ("", "localhost", "127.0.0.1", ".ngrok-free.app")]

# Add ngrok host at runtime if provided
ngrok_domain = os.getenv("NGROK_DOMAIN", "")
if ngrok_domain:
    ALLOWED_HOSTS = list(ALLOWED_HOSTS) if isinstance(ALLOWED_HOSTS, (list, tuple)) else []
    ALLOWED_HOSTS += [ngrok_domain]

    # Django 4+ requires full scheme in CSRF_TRUSTED_ORIGINS
    if "CSRF_TRUSTED_ORIGINS" in globals():
        CSRF_TRUSTED_ORIGINS = list(CSRF_TRUSTED_ORIGINS)
    else:
        CSRF_TRUSTED_ORIGINS = []
    CSRF_TRUSTED_ORIGINS.append(f"https://{ngrok_domain}")
'''


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',                         # This is the main or core application for the system
    'accounts',
    'pdk_calendar',
    'intake',
    'clearing',
    'acknowledgments',
    'review',
    'billing.apps.BillingConfig',
    'analytics',
    'client_portfolio',

    'rest_framework',
    'crispy_forms',
    'crispy_bootstrap5',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

AUTH_USER_MODEL = 'accounts.InternalUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pdk_crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'pdk_crm' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.nav_apps',
            ],
        },
    },
]

WSGI_APPLICATION = 'pdk_crm.wsgi.application'


# Database
USE_SQLITE = os.getenv("USE_SQLITE", "False").strip().lower() in ("1", "true", "yes", "on")
if USE_SQLITE:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "var" / "db.sqlite3",
        }
    }
else:
    # https://docs.djangoproject.com/en/5.2/ref/settings/#databases
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',  #NOTE: RDBMS set to PostgreSQL
            'NAME': os.getenv("DB_NAME"),
            'USER': os.getenv("DB_USER"),
            'PASSWORD': os.getenv("DB_PASSWORD"),
            'HOST': os.getenv("DB_HOST", "crm_db"),
            'PORT': os.getenv("DB_PORT", "5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# where source static assets live
STATICFILES_DIRS = [BASE_DIR / "static"]

# where 'collectstatic' will gather everything for development
STATIC_ROOT = BASE_DIR / "staticfiles"

# media uploads (user-generated files)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Authentication settings
LOGIN_URL = 'accounts:login'                # where @login_required redirects if not logged in
LOGOUT_REDIRECT_URL = 'accounts:login'      # where LogoutView redirects
LOGIN_REDIRECT_URL = 'core:home'            # where to go after login


# Session & security options
SESSION_COOKIE_AGE = 60 * 60 * 2            # 2 hour cookies session
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True           # resets session expiration while user is actively in system