# Generated by Django 5.2.1 on 2026-06-01 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0032_phase1_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('review_started_at', models.DateTimeField(blank=True, null=True)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_reviewer', models.ForeignKey(blank=True, help_text='Last staff member who started review (not an exclusive lock).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_assignments', to=settings.AUTH_USER_MODEL)),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_review_entries', to=settings.AUTH_USER_MODEL)),
                ('product_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_entry', to='core.productassignment')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
